global:
  scrape_interval: 30s

rule_files:
  - /etc/prometheus/prometheus-recording.rules.yml
  - /etc/prometheus/postgres-alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'rover_ingest'
    scrape_interval: 10s
    static_configs:
      - targets: ['rover_ingest:9109']
