data:
  train_dir: "C:/Users/משתמש/Desktop/vectordb_efrat/Datasets/Fruit and Vegetable Disease - Healthy vs Rotten/train"
  val_dir:   "C:/Users/משתמש/Desktop/vectordb_efrat/Datasets/Fruit and Vegetable Disease - Healthy vs Rotten/val"
  test_dir:  "C:/Users/משתמש/Desktop/vectordb_efrat/Datasets/Fruit and Vegetable Disease - Healthy vs Rotten/test"

model:
  backbone: "mobilenet_v3_small" 
  img_size: 192

train:
  epochs: 8
  batch_size: 32
  lr: 3e-4
  weight_decay: 1e-4

inference:
  img_size: 192

paths:
  best_weights: "outputs/fruit_cls_best.pt"
