global:
  scrape_interval: 5s

scrape_configs:
  - job_name: minio-hot
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio-hot:9000']  
  - job_name: minio-cold
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio-cold:9000']  
