# prometheus.yml 
global:
  scrape_interval: 15s 

rule_files:
  - /etc/prometheus/prometheus-recording.rules.yml
  - /etc/prometheus/postgres-alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 
        
scrape_configs:
  # Sensors metrics (GUI)
  - job_name: 'sensors-demo'
    static_configs:
      - targets: ['sensors_metrics:8000']

  # Postgres exporter (RelDB)
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
