services:

  data-publisher:
    build: .
    container_name: security-publisher
    # env_file: .env
    volumes:
      - ../data/security:/security:ro
    command: ["python", "-u", "/app/data_publisher.py"]

  # sound-publisher:
  #   build: .
  #   # image: data-publisher:latest  # or 'build: .' again if you prefer
  #   container_name: sound-publisher
  #   env_file: .env.sound           # separate env file for sound topics/ids
  #   volumes:
  #     - ./data/sound/sounds:/data/sound/sounds:ro    
  #     - ./data/sound/metadata:/data/sound/metadata:ro     
  #   command: ["python", "-u", "/app/data_publisher.py"]

networks:
  default:
    external: true
    name: agcloud_ag_cloud
