teams:
  air:
    metadata_topic: aerial_images_metadata
    minio_topic: image.new.aerial 
    output_topic: image_new_aerial_connections
  security:
    metadata_topic: dev-security-images-keys
    minio_topic: image.new.security
    output_topic: image_new_security_connections


  # fruits:
  #   metadata: dev-fruits-images-keys
  #   minio: image.new.fruits
  #   output: image.new.fruits.connections

 
