version: "3.9"

services:
  contracts-gen:
    build:
      context: .
      dockerfile: app/contracts/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://missions_user:pg123@host.docker.internal:5432/missions_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app/contracts:/app/app/contracts
    networks: [airnet]
    restart: "no"

  api:
    build:
      context: .
    env_file:
      - .env
    environment:
        DB_DSN: postgresql+psycopg://missions_user:pg123@host.docker.internal:5432/missions_db
    volumes:
      - ./app/contracts:/app/app/contracts
    ports:
      - "8080:8080"
    depends_on:
      contracts-gen:
        condition: service_completed_successfully
    networks: [airnet]
    restart: unless-stopped

networks:
  airnet:
    name: airnet
    driver: bridge


